---
driver:
  name: vagrant
  require_chef_omnibus: 12.18.31
provisioner:
  name: chef_zero
  clients_path: test/fixtures/clients

platforms:
- name: centos-7
  driver_config:
    box: bento/centos-7.1
- name: windows-2012
  driver_config:
    box: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[test-secrets]
